steps:
  # Build Step
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      # Pass the NEXT_PUBLIC_GOOGLE_PLACES_API_KEY as a build argument
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$(NEXT_PUBLIC_GOOGLE_PLACES_API_KEY)'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '.'
      - '-f'
      - Dockerfile
    id: Build
    # Provide the secret environment variable to this step
    secretEnv:
      - NEXT_PUBLIC_GOOGLE_PLACES_API_KEY

  # Push Step
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  # Deploy Step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      # Set server-side environment variables from Secret Manager
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets'
      - 'GOOGLE_PLACES_API_KEY=GOOGLE_PLACES_API_KEY:latest'
      - '--set-secrets'
      - 'NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=NEXT_PUBLIC_GOOGLE_PLACES_API_KEY:latest'
    id: Deploy
    # Provide the secret environment variables to this step
    secretEnv:
      - OPENAI_API_KEY
      - GOOGLE_PLACES_API_KEY
      - NEXT_PUBLIC_GOOGLE_PLACES_API_KEY

images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

# Define the secrets available during the build and deploy steps
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_PLACES_API_KEY/versions/latest'
      env: 'NEXT_PUBLIC_GOOGLE_PLACES_API_KEY'
    - versionName: 'projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest'
      env: 'OPENAI_API_KEY'
    - versionName: 'projects/$PROJECT_ID/secrets/GOOGLE_PLACES_API_KEY/versions/latest'
      env: 'GOOGLE_PLACES_API_KEY'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: plan-my-trip
  REPO_NAME: plan-my-trip
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 586b1c24-d7d4-41ce-a4ac-57c5f6fcaa11

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - plan-my-trip
